name = "cf-rss"
compatibility_date = "2024-02-24"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./dist"

[build]
command = "npm run build"
directory = "dist"

[build.upload]
format = "service-worker"

[env.production]
pages_build_output_dir = "dist"

[functions]
directory = "functions" 